#!/bin/bash
set -e

echo "Creating databases and users..."

echo "Database: ${MARIADB_DATABASE_JUPYTERHUB}"
mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS \`${MARIADB_DATABASE_JUPYTERHUB}\`
        CHARACTER SET utf8mb4
        COLLATE utf8mb4_unicode_ci;
    CREATE USER IF NOT EXISTS '${MARIADB_USER_JUPYTERHUB}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD_JUPYTERHUB}';
    GRANT ALL PRIVILEGES ON \`${MARIADB_DATABASE_JUPYTERHUB}\`.* TO '${MARIADB_USER_JUPYTERHUB}'@'%';
    FLUSH PRIVILEGES;
EOSQL

if [ -n "$MARIADB_DATABASE_MOODLE" ]; then
echo "Database: ${MARIADB_DATABASE_MOODLE}"
mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS \`${MARIADB_DATABASE_MOODLE}\`
        CHARACTER SET utf8mb4
        COLLATE utf8mb4_unicode_ci;
    CREATE USER IF NOT EXISTS '${MARIADB_USER_MOODLE}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD_MOODLE}';
    GRANT ALL PRIVILEGES ON \`${MARIADB_DATABASE_MOODLE}\`.* TO '${MARIADB_USER_MOODLE}'@'%';
    FLUSH PRIVILEGES;
EOSQL
fi
