base_dir: "/srv/jupyterhub"
certs_dir: "{{base_dir}}/certs"
jupyterhub_dir: "{{base_dir}}/jupyterhub"
notebook_dir: "{{base_dir}}/notebook"
jupyterhub_image_dir: "{{jupyterhub_dir}}/jupyterhub"
notebook_image_dir: "{{notebook_dir}}/image"
gid_teacher: 600
gid_student: 601